FROM quay.io/pypa/manylinux_2_28
  
# Set a working directory
WORKDIR /app
COPY . .

ARG PYTHON_VERSION="cp39-cp39"

# Print the GLIBC version
RUN ldd --version && \

# Install and test with Python ${PYTHON_VERSION}
   /opt/python/${PYTHON_VERSION}/bin/pip install -r ./requirements.txt && \

# Install the package from local dist directory
   /opt/python/${PYTHON_VERSION}/bin/pip install PalletJack --pre --find-links ./dist --only-binary=:all: && \

# Force reinstall to ensure local version is used
   /opt/python/${PYTHON_VERSION}/bin/pip install PalletJack --pre --find-links ./dist --only-binary=:all: --force-reinstall --no-index --no-deps

# Define the command to run tests
CMD ["/opt/python/${PYTHON_VERSION}/bin/python", "./test/test_palletjack.py"]
