# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python-ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      working-directory: ./python
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt
        pip install cibuildwheel auditwheel

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      working-directory: ./python
      run: |
        python3 setup.py develop
        pytest

    - name: Build sdist
      working-directory: ./python
      run: |
        python setup.py build_ext sdist

    - name: Build wheels
      if: runner.os <> 'macos'
      working-directory: ./python
      run: python -m cibuildwheel --output-dir dist
      # to supply options, put them in 'env', like:
      env:
        CIBW_REPAIR_WHEEL_COMMAND_LINUX: auditwheel repair --exclude libarrow.so.1400 --exclude libparquet.so.1400 -w {dest_dir} {wheel}
        CIBW_ENVIRONMENT: CYTHONIZE=1
        CIBW_BUILD_VERBOSITY: 1
        # Disable unsupported builds
        CIBW_SKIP: "pp* *_i686 *-musllinux_* *win32" 
        # CIBW_BUILD: "cp3*-manylinux_x86_64"

    - uses: actions/upload-artifact@v4
      with:
        name: dist-${{ matrix.os }}
        path: ./python/dist/*