# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Python-cd

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Build sdist
        working-directory: ./python
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install -r requirements.txt
          python setup.py build_ext sdist
          
      - name: Validate tag and package version
        working-directory: ./python
        shell: pwsh
        run: |

          if ("${{ github.ref }}" -like "refs/tags/v*") {
              $tag = "${{ github.ref }}".SubString(11)
              $expectedFile = "dist/palletjack-$tag.tar.gz"

              # Check whether the tag and the package version match together
              if (-not (Test-Path -Path $expectedFile)) {
                  echo "::error ::Expected file $expectedFile doesn't exist"
                  exit 1
              }
          }  

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@c12cc61414480c03e10ea76e2a0a1a17d6c764e2
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: python/dist		  
