# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python-ci

on:
  push:

permissions:
  contents: read

jobs:
  pytest:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install thrift (Windows)
      working-directory: ./python
      if: runner.os == 'windows'
      run: |
        vcpkg install --triplet x64-windows --x-manifest-root . --feature-flags=versions --clean-after-build

    - name: Install thrift (Linux)
      if: runner.os == 'linux'
      run: |
        sudo apt-get install -y libthrift-dev libboost-all-dev

    - name: Install thrift (macOS)
      if: runner.os == 'macos'
      run: |
        brew install thrift

    - name: Install dependencies
      working-directory: ./python
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      working-directory: ./python
      run: |
        pip install --editable . 
        pytest
